### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RyuaNerin** [RyuaNerin/DNS-For-Twimg#1]
- [x] no CNAME

**Comment by RyuaNerin** [comment]
- [ ] 테스트 결과 바로 드롭하지 않고 측정해보고 몇번 성공했는지 % 로 보여주기
- [ ] 메인 홈페이지에서 CDN 연결상태 확인할 수 있도록 해주기

**Comment by RyuaNerin** [comment]
- [ ] 기타 호스트 추가 (샘플 데이터 필요)
